#!/bin/bash
# -----------------------------------------------------------------------------
# fix-duplicate-setter.sh
#
# Removes ALL fluent setters generated by OpenAPI Generator.
# Keeps JavaBean setters (void setXxx) for Jackson compatibility.
#
# Fixes method collisions like:
#   setDescription(String)
#   setSetDescription(String)
# -----------------------------------------------------------------------------

set -euo pipefail

OUT_DIR="$1"
SRC_DIR="$OUT_DIR/src/main/java"

echo "🧹 Removing fluent setters (collision-safe fix)"

find "$SRC_DIR" -name "*.java" | while read -r file; do
  awk '
    BEGIN { skip=0 }

    # Detect fluent setter (returns model type, not void)
    /public [A-Za-z0-9_]+ set[A-Za-z0-9_]+\(/ {
      if ($0 ~ /public void set/) {
        print
        next
      }
      skip=1
      next
    }

    skip && /^\s*\}/ {
      skip=0
      next
    }

    !skip { print }
  ' "$file" > "$file.tmp" && mv "$file.tmp" "$file"
done

echo "✅ Fluent setters removed"
